# Generated by Django 3.2.13 on 2023-07-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='credito',
            field=models.IntegerField(default=100),
        ),
    ]
